package com.example.projeto.misc;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.util.Log;

public class    AlarmReceiver extends BroadcastReceiver {
    MqttHelper helper;
    String brookerUri;
    String clientId;
    @Override
    public void onReceive(Context context, Intent intent) {
        // This method will be called when the alarm is triggered.
        // You can perform your background task here.
        Log.w("RING","RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING ");


        // You can also start the MessageReceiver IntentService here
        Intent serviceIntent = new Intent(context, MessageReceiver.class);
        context.startService(serviceIntent);
    }
}



