package com.example.projeto;

import static androidx.constraintlayout.helper.widget.MotionEffect.TAG;
import static androidx.legacy.content.WakefulBroadcastReceiver.startWakefulService;

import android.app.AlarmManager;
import android.app.IntentService;
import android.app.PendingIntent;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.nfc.Tag;
import android.util.Log;

import androidx.legacy.content.WakefulBroadcastReceiver;

public class AlarmReceiver extends BroadcastReceiver {
    MqttHelper helper;
    String brookerUri;
    String clientId;
    @Override
    public void onReceive(Context context, Intent intent) {
        // This method will be called when the alarm is triggered.
        // You can perform your background task here.
        Log.w("RING","RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING RING ");


        // You can also start the MessageReceiver IntentService here
        Intent serviceIntent = new Intent(context, MessageReceiver.class);
        context.startService(serviceIntent);
    }
}



